language: android
jdk: oraclejdk8
sudo: false
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_EMULATOR_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - QEMU_AUDIO_DRV=none
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$ANDROID_EMULATOR_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-$ANDROID_ABI-$ANDROID_TAG-$ANDROID_EMULATOR_LEVEL
before_install:
- yes | sdkmanager "platforms;android-28"
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache/"
before_script:
- android list targets
- echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL
  --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-window &
- android-wait-for-emulator
- pwd
- ls -l
script: "./gradlew build connectedCheck"
after_failure:
- cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml
deploy:
  provider: releases
  api_key:
    secure: iirfwuNFCcy5ZjQqJH0tcSAOiCGhzOdb/mIIS/ln3I0axQu3lpSH6AZCwzpKQeVsEXIpDAk6EONvjpj0oePfUd36O8rvkqXmFWhNBCfsfQr2afHu7oW5N8BU9XhiRqAx68lDPKQGLRUrckrAy0pI47tkR/a0QgIEHj4Dgpk8rodTFzKNTwUhYBPw1gBmARyBqzmxiyTiroi559IfRxf07lR5FDPtq4WyDLeZ10wOKxzVqWs6vfwH8gjD8gv8zcmcYdvAJKqsQG7nn9t5Bv//xsHA1mcnqHc6P3oFQ+AnEh+h/hLvUp0L9JghnWxKBoxko5YPKeM43DWYDkNVkXwUv15rKRHYgNau3bqLWlDol3mgciTy5uR63DQ98rf2/ZXQKA1txMNBXtUHfwe1swp91nOSh8cdxhORW9MbBaDGG5A2JC/pxMwPwy4qRznCL8wQZG0To085peQ9QJhH2m5kvhA42N0hbvpSLhwfAYr3IlhKUhQ1RUxYJBFqoyF24WCLVlLYMRAlqRc9v6IsQMd/ALTBhlFt9DQKq7k4BS4TvCh46W42DTHD1qWrTyKW3lL/je5KlkGF2rb8ZEPoP9Mh90118wB+m9obE1wFvbByeK8vcZWgcVeiiousr49WKkazvqQsim7z4rRXmJeFhTqiFnCwxrwPLKtUd8eZLBljEL0=
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  on:
    repo: drockwood94/TravisCITest
